export 'package:catbreeds/src/paginas/BreedScreen.dart';
export 'package:catbreeds/src/paginas/SplashScreen.dart';
//export 'package:catbreeds/src/paginas/cuidador.dart';
//export 'package:catbreeds/src/paginas/indicadores_pu.dart' hide Task;
//export 'package:catbreeds/src/paginas/indicadores.dart';
//export 'package:catbreeds/src/paginas/inicial.dart';
//export 'package:catbreeds/src/paginas/iniciar_sesion.dart';
//export 'package:catbreeds/src/paginas/mapa_inicio.dart';
//export 'package:catbreeds/src/paginas/modificar_cuenta.dart';
//export 'package:catbreeds/src/paginas/novedadades_usuario.dart';
//export 'package:catbreeds/src/paginas/novedades_reportes.dart';
//export 'package:catbreeds/src/paginas/qr_page.dart';
//export 'package:catbreeds/src/paginas/recuperar_clave.dart';
//export 'package:catbreeds/src/paginas/registro.dart';
//export 'package:catbreeds/src/paginas/buscador_sigau.dart';
